# Generated by Django 3.1.11 on 2021-07-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210606_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='store',
        ),
    ]
